name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Test
      run: go test -gcflags=-l ./...
    - name: Build DB
      run: go build ./cmd/sxcctw_db
    - name: Build API
      run: go build ./cmd/sxcctw_api
