name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build DB
      run: cd db && go build -v ./...

    - name: Test DB
      run: cd db && go test -v ./...
      
    - name: Build Server
      run: cd server && go build -v ./...

    - name: Test Server
      run: cd server && go test -v ./...
